INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("aart", "https://www.twitch.tv/aartdappels", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("aart-net", "https://mega.nz/#!6dwTwCxb!pYlo7A9xiVT7csP-V2lqBTmrss5EOhda5NiEG51wD4Y", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("ankan", "https://www.twitch.tv/ankanban", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("benchmarks", "https://docs.google.com/spreadsheets/d/1lGFf6PLGmBUSMan-YP7Vul4DpRNfn6K8oeCjBILe6uA/edit?usp=sharing", "Leela performance on different GPU/CPU configurations", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("blog", "https://blog.lczero.org/", "Project blog", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("board", "http://testtraining.lczero.org", "Tensorboard, you can watch training graphs there", 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("careless", "https://www.twitch.tv/careless25", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("ccc", "https://www.chess.com/computer-chess-championship", "Chess.com Computer Chess Championship", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("ccc3", "https://www.chess.com/news/view/computer-chess-championship-back-for-rapid-redux", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("cccc", "https://www.chess.com/computer-chess-championship", "Chess.com Computer Chess Championship", 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("ccccc", "https://www.chess.com/computer-chess-championship", "Chess.com Computer Chess Championship", 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("ccls", "https://www.twitch.tv/ccls", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("ccrl", "https://docs.google.com/spreadsheets/d/1XSJiCcQpCLv0fNwrUn7jXjdkZFU63YFEWpdXv6dSSg0/htmlview", "CCRL rating estimate", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("chat", "https://discord.gg/pKujYxD", "Our project Discord server", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("cheat-sheet", "https://applied-data.science/static/main/res/alpha_go_zero_cheat_sheet.png", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("cheatsheet", "https://applied-data.science/static/main/res/alpha_go_zero_cheat_sheet.png", "AlphaGo Neural Network diagram (AlphaZero/Lc0 is similar)", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("colab", "https://github.com/LeelaChessZero/lc0/wiki/Run-Leela-Chess-Zero-client-on-a-Tesla-K80-GPU-for-free-(Google-Colaboratory)", "How to setup Lc0 training on colab", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("colab-testing", "https://docs.google.com/spreadsheets/d/1XfVXmDx0eU_zT-kVCE-cyjABeumDq_AfoBgMZ2YTf5Y/edit#gid=1192931852", "Test for TCEC S15 network selection", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("contributions", "https://app.powerbi.com/view?r=eyJrIjoiYjhhZWMyNGUtZDI2Ny00OTI2LWIzOTgtN2YzZDIwOWQxNmMyIiwidCI6Ijk4NTE5NjM1LThlZGUtNDU1NS05MTk4LWRlNGU4NjJkNzEyNSIsImMiOjZ9", "Graph of number of generated games per day", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("cpuct", "https://medium.com/oracledevs/lessons-from-alphazero-part-3-parameter-tweaking-4dceb78ed1e5#4ed9", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("decoder", "https://github.com/LeelaChessZero/lc0/wiki/Getting-Started#debug-output", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("drops", "https://docs.google.com/spreadsheets/d/16vwCrq8c9eveF0kGGzn8hP_IFX4rFsfB548aD6QYUhU/htmlview", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("elosummary", "https://docs.google.com/spreadsheets/d/1Mi2qwPCK4aVNt9B8aC-HecIyLJ0BEAPvp63L59DTrY4", "Compilations of various ELO graphs/estimations", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("endgames", "https://docs.google.com/spreadsheets/d/1dP8NCwyGOdkc0NuU4AQAFf-tnBeP_iSTnGJR-lrp8EM/htmlview", "Endgame network performance against tablebase", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("formula", "https://github.com/LeelaChessZero/lc0/blob/release/0.21/src/mcts/search.cc#L128", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("github", "https://github.com/LeelaChessZero/", "Our GitHub project page", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("history", "https://github.com/LeelaChessZero/lc0/wiki/Project-History", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("jj", "https://docs.google.com/spreadsheets/d/1yxri9LRpVH2TMWjgUDuw-V2jfpNs0pkNqNNJ3sHuttA/htmlview", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("jjosh", "https://www.twitch.tv/jjoshua2", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("lc0", "https://github.com/LeelaChessZero/lc0/wiki/Getting-Started", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("leela-elo", "https://github.com/LeelaChessZero/lc0/wiki/FAQ#where-can-i-find-leela-chess-zeros-current-elo", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("matches", "http://lczero.org/matches", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("matt", "https://www.twitch.tv/mattblachess", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("nn-terms", "https://docs.google.com/spreadsheets/d/1ZAIuHR6n-5JTxKQc0XUSx1jyUrgVEcj8DNLKA7-urBw/htmlview", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("notify", "https://github.com/LeelaChessZero/lc0/wiki/Whom-to-notify", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("openbench", "http://ec2-34-217-73-2.us-west-2.compute.amazonaws.com:8000/", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("openings", "https://script.google.com/macros/s/AKfycbwAVsblBYs17sxoao9wKiz88m2FfBG-154ncQ1lPEC8M1vXQ5T9/exec", "Openings frequency per network ID", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("ordo", "https://discordapp.com/channels/425419482568196106/530486338236055583/530499162102431754", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("other-nets", "https://github.com/LeelaChessZero/lc0/wiki/Third-Party-Nets", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("position-test", "https://docs.google.com/spreadsheets/d/1MeCqY05v41ojhnejrqSy2cUSfVhjYEAFbfNCn13cyH8/htmlview", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("potato", "https://www.twitch.tv/potato_chess", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("releases", "https://github.com/LeelaChessZero/lc0/releases", "Lc0 releases to download", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("se", "https://towardsdatascience.com/squeeze-and-excitation-networks-9ef5e71eacd7", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("sheet", "https://docs.google.com/spreadsheets/d/1zcXqNzLNBT8RjTHO_AppL6WN0j8TGmOIh6osLPmaB6E/htmlview", "Aloril's spreadsheet comparing Lc0 strength with StockFish at various fixed nodes per move", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("sheet2", "https://docs.google.com/spreadsheets/d/1ZAIuHR6n-5JTxKQc0XUSx1jyUrgVEcj8DNLKA7-urBw/htmlview", "Cscuile's Engine rating list", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("sheet3", "https://docs.google.com/spreadsheets/d/19UL5a9I3M_TjIYwTpJQKdCi2RJHpxDD9YHnRogrwTnc/htmlview", "Another Lc0 rating estimation", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("sheet4", "https://docs.google.com/spreadsheets/d/1QxAG6XVTvvTAGlZ-kpSSvv0VuMGh7RkJjgKqgT37vMU/htmlview", "Yet another Lc0 rating estimation", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("sheet5", "https://docs.google.com/spreadsheets/d/18UWR4FVhPi0vNwwPreu_avd9ycujGQ5ayR2LzJOWP4s/htmlview#gid=0", "And one more another Lc0 rating estimation", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("swa", "https://towardsdatascience.com/stochastic-weight-averaging-a-new-way-to-get-state-of-the-art-results-in-deep-learning-c639ccf36a", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("t40fork", "https://docs.google.com/spreadsheets/d/1-KAIfcaq5gwT90AlFNlqAWsmOehrCks86A88V47LDO0/htmlview", "An Lc0 fork of test40 run by jhorthos", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("tcec", "http://tcec.chessdom.com/live.php", "Top Chess Engine Championship", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("tensorboard", "http://testtraining.lczero.org", "Tensorboard, you can watch training graphs there", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("test-openings", "https://script.google.com/macros/s/AKfycbywkdQQKQjCEWJ_Pg_B08MCCWruu8wEE_VUag-Gxkc2FKeJNu0/exec", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("tests", "http://mind-research.com/LeelaChess/DiscordTestDB/", "Automatic beautiful compilation of tests from discord #test-results", 1);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("time", "https://www.timeanddate.com/worldclock/personal.html?cities=240,48,179,64,224", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("watch-leela", "https://github.com/LeelaChessZero/lc0/wiki/FAQ#can-i-watch-leela-chess-zero-play-somewhere", NULL, 0);
INSERT OR REPLACE INTO urls (url, redirect, comment, featured) VALUES ("wiki", "https://github.com/LeelaChessZero/lc0/wiki", "Project wiki on GitHub", 1);